name: drleelm
services:
  - name: backend
    dockerfile_path: Dockerfile
    github:
      repo: fenago/drleelm
      branch: main
      deploy_on_push: true
    http_port: 5000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    # Increase HTTP route timeout to handle LLM API calls
    cors:
      allow_origins:
        - prefix: "*"
      allow_methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      allow_headers:
        - Content-Type
        - Authorization
